name: Deploy to Production Environment
on:
  push:
    branches:
      - 'release'
jobs:
  deploy-prod:
    environment:
      name: production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - name: Install dependencies
        run: npm install
      - name: Lint Code
        run: npm run lint
      - name: Build and Compile Typescript
        run: npm run build
      - name: Deploy to Heroku Production Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
          heroku_app_name: 'co-caesar'
          heroku_email: 'joshua@nonsensecodes.io'
          procfile: 'worker: npm run prod'
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.PROD_DISCORD_TOKEN}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.PROD_BOT_PUBLIC_KEY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.PROD_BOT_APPLICATION_ID}}
          HD_DD_API_KEY: ${{secrets.PROD_DD_API_KEY}}
          HD_SENTRY_IO_DSN: ${{secrets.PROD_SENTRY_IO_DSN}}
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          sourcemaps: './dist'
        with:
          environment: 'production'
          version: 'caesar@${{ steps.package-version.outputs.current-version }}'
          sourcemaps: './dist'